ci: pref ci build workflows

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -27,6 +27,8 @@ jobs:
           SSH_USER: ${{ secrets.SSH_USER }}
           SERVER_PATH_REMOTE: ${{ secrets.SERVER_PATH_REMOTE }}
           APP_NAME: nest-oss
+          MAX_RETRIESL: 5
+          RETRY_COUNT: 0
         run: |
           mkdir -p ~/.ssh
           echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
@@ -34,7 +36,22 @@ jobs:
           ssh-keyscan $SSH_HOST >> ~/.ssh/known_hosts
           ssh $SSH_USER@$SSH_HOST  << EOF
             cd $SERVER_PATH_REMOTE
-            git pull origin server
+
+            while [ \$RETRY_COUNT -lt \$MAX_RETRIES ]; do
+              if git pull origin doc; then
+                break  # pull succesful exit
+              else
+                echo "Git pull failed, retrying (\$((RETRY_COUNT + 1)) of \$MAX_RETRIES)..."
+                ((RETRY_COUNT++))
+                sleep 5
+              fi
+            done
+
+            # check if retry count exceeded
+            if [ \$RETRY_COUNT -eq \$MAX_RETRIES ]; then
+              echo "Failed to pull code after \$MAX_RETRIES attempts. Exiting."
+              exit 1  # throw error
+            fi
             npm install
             npm run build
             pm2 restart $APP_NAME || pm2 start dist/src/main.js --name $APP_NAME
