feat: pull request add retry

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -33,7 +33,23 @@ jobs:
           chmod 600 ~/.ssh/id_rsa
           ssh-keyscan $SSH_HOST >> ~/.ssh/known_hosts
           ssh $SSH_USER@$SSH_HOST  << EOF
-            cd $BLOG_PATH_REMOTE
-            git pull origin doc
-            pm2 restart $APP_NAME || pm2 start "docsify s" --name $APP_NAME
+          cd $BLOG_PATH_REMOTE
+          # 循环尝试拉取代码
+          while [ \$RETRY_COUNT -lt \$MAX_RETRIES ]; do
+            if git pull origin doc; then
+              break  # 如果成功拉取，则跳出循环
+            else
+              echo "Git pull failed, retrying (\$((RETRY_COUNT + 1)) of \$MAX_RETRIES)..."
+              ((RETRY_COUNT++))
+              sleep 5  # 等待5秒后重试
+            fi
+          done
+
+          # 检查是否达到了最大重试次数
+          if [ \$RETRY_COUNT -eq \$MAX_RETRIES ]; then
+            echo "Failed to pull code after \$MAX_RETRIES attempts. Exiting."
+            exit 1  # 抛出异常并退出进程
+          fi
+
+          pm2 restart $APP_NAME || pm2 start "docsify s" --name $APP_NAME
           EOF
