ci: pref ci build workdflows

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -27,6 +27,8 @@ jobs:
           SSH_USER: ${{ secrets.SSH_USER }}
           BLOG_PATH_REMOTE: ${{ secrets.BLOG_PATH_REMOTE }}
           APP_NAME: docsify-blog
+          MAX_RETRIESL: 5
+          RETRY_COUNT: 0
         run: |
           mkdir -p ~/.ssh
           echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
@@ -34,25 +36,21 @@ jobs:
           ssh-keyscan $SSH_HOST >> ~/.ssh/known_hosts
           ssh $SSH_USER@$SSH_HOST  << EOF
           cd $BLOG_PATH_REMOTE
-          # 设置重试次数和计数器
-          MAX_RETRIES=10
-          RETRY_COUNT=0
 
-          # 循环尝试拉取代码
           while [ \$RETRY_COUNT -lt \$MAX_RETRIES ]; do
             if git pull origin doc; then
-              break  # 如果成功拉取，则跳出循环
+              break  # pull succesful exit
             else
               echo "Git pull failed, retrying (\$((RETRY_COUNT + 1)) of \$MAX_RETRIES)..."
               ((RETRY_COUNT++))
-              sleep 5  # 等待5秒后重试
+              sleep 5
             fi
           done
 
-          # 检查是否达到了最大重试次数
+          # check if retry count exceeded
           if [ \$RETRY_COUNT -eq \$MAX_RETRIES ]; then
             echo "Failed to pull code after \$MAX_RETRIES attempts. Exiting."
-            exit 1  # 抛出异常并退出进程
+            exit 1  # throw error
           fi
 
           pm2 restart $APP_NAME || pm2 start "docsify s" --name $APP_NAME
